config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions"
  }
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  root to: "home#index"
  resources :users, only: [:index, :edit, :update, :destroy]
  resources :works
  resources :admin_users, only: [:index]
  resources :admin_works

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :works, dependent: :destroy
  with_options presence: true do
    validates :name
    validates :user_no
    validates :email
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  layout 'admin_application'
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.all
    render :layout => 'admin_application'
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path, notice: '更新に成功しました'
    else
      render :edit
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path, notice: '削除しました'
  end

  private
  def user_params
    params.require(:user).permit(:name, :user_no, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "社員編集") %>

<%= render 'shared/error_messages' %>
<h1 class="main-title text-white">Web日報登録</h1>
<%= form_with model: @user, local: true, class: "border rounded bg-white form-login" do |f| %>
  <h2 class="h3 my-3">社員編集（<%= @user.name %>）</h2>
  <div class="field">
    <%= f.text_field :name, class: "form-control rounded-pill mb-3 pt-3", autofocus: true, autocomplete: "email", placeholder: "名前" %>
  </div>
  <div class="field">
    <%= f.text_field :user_no, class: "form-control rounded-pill mb-3", autofocus: true, autocomplete: "email", placeholder: "社員番号 (数字4文字)" %>
  </div>
  <div class="field">
    <%= f.email_field :email, class: "form-control rounded-pill mb-3", autofocus: true, autocomplete: "email", placeholder: "メールアドレス" %>
  </div>
  <div class="actions">
    <%= f.submit "更新", class: "btn btn-primary rounded-pill px-5 my-4" %>
  </div>
<% end %>

app/views/users/index.html.erb
<% provide(:title, "社員一覧") %>

<h1 class="main-title text-white">Web日報登録（<%= current_admin.name %>）</h1>
<div class="border rounded bg-white form-user-list">
  <h2 class="h3 my-3">社員一覧</h2>
  <table class="table table-bordered">
    <thead>
      <tr class="bg-light">
        <th scope="col">社員番号</th>
        <th scope="col">社員名</th>
        <th scope="col">勤怠</th>
        <th scope="col">編集</th>
        <th scope="col">メールアドレス</th>
        <th scope="col">削除</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <th scope="row"><%= user.user_no %></th>
          <td><%= user.name %></td>
          <td>
            <%= link_to admin_works_path(id: user.id) do %>
              <i class="far fa-calendar-alt"></i>
            <% end %>
          </td>
          <td>
            <%= link_to edit_user_path(id: user.id) do %>
              <i class="fas fa-pen"></i>
            <% end %>
          </td>
          <td><%= user.email %></td>
          <td>
            <%= link_to  user_path(id: user.id), method: :delete, data: {confirm: "削除しますか？"} do %>
              <i class="fas fa-backspace"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>