config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions"
  }
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  root to: "home#index"
  resources :users, only: [:index, :edit, :update, :destroy]
  resources :works
  resources :admin_users, only: [:index]
  resources :admin_works

end

app/controllers/admin_works_controller.rb
class AdminWorksController < ApplicationController
  before_action :authenticate_admin!

  layout 'admin_application'
  def index
    @user = User.find(params[:id])
    @works = @user.works.order(date: 'ASC')

    @today = Date.today

    #当月か選択月を変数に代入
    if params[:date]
      @yyyymm = params[:date]
    else
      @yyyymm = Date.today.strftime('%Y/%m')
    end

    # 1ヶ月分の日数
    @days = Array(("#{@yyyymm}-01").to_date.all_month).size

    # 詳細モーダルの変数用
    @work = Work.new
    @modal_start_time = ""
    @modal_end_time = ""
    @modal_break_time = "01:00"
    @modal_comment = ""
  end

  def new
    @work = Work.new
  end

  def create

    @work = Work.new(work_params)
    date = @work.date.strftime('%Y-%m')
    user_id = @work.user_id

    if @work.save
      redirect_to admin_works_path(date: date, id: user_id), notice: '登録に成功しました'
    else
      redirect_to admin_works_path(date: date, id: user_id), notice: '登録に失敗しました'
    end
  end

  def edit
    @user = User.find(params[:user_id])

    # 当日データの有無の確認
    if @work = @user.works.find_by(date: params[:id])
      @date = @work.date
      @modal_start_time = @work.start_time.strftime('%H:%M') if @work.start_time != nil
      @modal_end_time = @work.end_time.strftime('%H:%M') if @work.end_time != nil
      @modal_break_time = @work.break_time
      @modal_comment = @work.comment
    else
      @work = Work.new
      @date = params[:id].to_date
      @modal_start_time = ""
      @modal_end_time = ""
      @modal_break_time = "01:00"
      @modal_comment = ""
    end
  end

  def update
    @work = Work.find(params[:id])
    date = @work.date.strftime('%Y-%m')
    user_id = @work.user_id

    if @work.update(work_params)
      redirect_to admin_works_path(date: date, id: user_id), notice: '更新に成功しました'
    else
      redirect_to admin_works_path(date: date, id: user_id), notice: '更新に失敗しました'
    end
  end

  private
  def work_params
    params.require(:work).permit(:user_id, :date, :start_time, :end_time, :break_time, :comment)
  end
end

app/helpers/admin_works_helper.rb
module AdminWorksHelper
end

app/views/admin_works/edit.html.erb
<% provide(:title, "日報編集") %>

<h1 class="main-title text-white">Web日報登録（<%= current_admin.name %>）</h1>

<%= form_with model: [ :admin, @work ], local: true do |f| %>
<section>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <p></p>
        <h5 class="modal-title">日報編集（<%= @user.name %>）</h5>
        <%= link_to :back do %>
          <button class="btn btn-secondary btn-back">戻る</button>
        <% end %>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="alert alert-primary">
            <%= @date.strftime('%Y年%m月%d日') %>(<%= %w(日 月 火 水 木 金 土)[@date.wday] %>)
            <%= f.hidden_field :date, value: @date %>
            <%= f.hidden_field :user_id, value: @user.id %>
          </div>
          <div class="row">
            <div class="col-sm">
              <div class="input-group">
                <%= f.text_field :start_time, id: "modal_start_time", class: "form-control", placeholder: "出勤", value: @modal_start_time %>
                <div class="input-group-prepend">
                  <button type="button" class="input-group-text" id="start_btn">打刻</button>
                </div>
              </div>
            </div>
            <div class="col-sm">
              <div class="input-group">
                <%= f.text_field :end_time, id: "modal_end_time", class: "form-control", placeholder: "退勤", value: @modal_end_time %>
                <div class="input-group-prepend">
                  <button type="button" class="input-group-text" id="end_btn">打刻</button>
                </div>
              </div>
            </div>
            <div class="col-sm">
              <div class="input-group">
                <%= f.text_field :break_time, class: "form-control rounded", placeholder: "休憩", value: @modal_break_time %>
              </div>
            </div>
          </div>
          <div class="form-group pt-3">
            <%= f.text_area :comment, class: "form-control", size: "40x5", placeholder: "業務内容", value: @modal_comment, maxlength: 200 %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit "更新", class: "btn btn-primary rounded-pill px-5" %>
      </div>
    </div>
  </div>
</section>
<% end %>

<script>
  // 出勤打刻
  $('#start_btn').click(function () {
    const now = new Date();
    const hour = now.getHours().toString().padStart(2, '0');
    const minute = now.getMinutes().toString().padStart(2, '0');
    $('#modal_start_time').val(hour+':'+minute);   
  });
  // 退勤打刻
  $('#end_btn').click(function () {
    const now = new Date();
    const hour = now.getHours().toString().padStart(2, '0');
    const minute = now.getMinutes().toString().padStart(2, '0');
    $('#modal_end_time').val(hour+':'+minute);   
  });
</script>

app/views/admin_works/index.html.erb
<% provide(:title, "日報登録") %>

<h1 class="main-title text-white">Web日報登録（<%= current_admin.name %>）</h1>
<div class= "border rounded bg-white form-time-table">
  <h2 class="h3 my-3">月間データ（<%= @user.name %>）</h2>
  <form>
    <select class="form-control rounded-pill mb-3" name="date" onchange="submit(this.form)">
      <option value="<% @today.strftime('%Y-%m') %>"><%= @today.strftime('%Y/%m') %></option>
      <% for i in 1..12 %>
        <option value="<%= @today.ago(i.month).strftime('%Y-%m') %>"<%= "selected" if @yyyymm == @today.ago(i.month).strftime('%Y-%m') %>>
          <%= @today.ago(i.month).strftime('%Y/%m') %>
        </option>
      <% end %>
    </select>
    <input type='hidden' value='<%= @user.id %>' name="id">
  </form>
  <table class="table table-bordered">
    <thead>
      <tr class="bg-light">
        <th scope="col">日</th>
        <th scope="col">出勤</th>
        <th scope="col">退勤</th>
        <th scope="col">休憩</th>
        <th scope="col">業務内容</th>
        <th scope="col">詳細</th>
        <th scope="col">編集</th>
      </tr>
    </thead>
    <tbody>
      <% @days.times do |n| %>
        <% date = "#{@yyyymm}-#{format("%02d", n + 1)}".to_date %>
        <% start_time = "" %>
        <% end_time = "" %> 
        <% break_time = "" %>
        <% comment = "" %>
 
          <% @works.each do |work| %>
            <% if work.date == date %>
              <% date = work.date %>
              <% start_time = work.start_time.strftime('%H:%M') if work.start_time != nil %>
              <% end_time = work.end_time.strftime('%H:%M') if work.end_time != nil %> 
              <% break_time = work.break_time if work.break_time != nil %>
              <% comment = work.comment.truncate(20) if work.comment != nil %>              
            <% end %>
          <% end %>
         <tr>
          <th scope="row"><%= date.strftime('%-m/%-d') %>(<%= %w(日 月 火 水 木 金 土)[date.wday] %>)</th>
          <td><%= start_time %></td>
          <td><%= end_time %></td>
          <td><%= break_time %></td>
          <td><%= comment %></td>
          <td>
            <button type="button" class="btn h-auto py-0" data-toggle="modal" data-target="#inputModal-edit" data-day="<%= date.strftime('%Y-%m-%d') %>">
              <i class="fas fa-book-open"></i>
            </button>
          </td>
          <td>
            <%= link_to edit_admin_work_path(id: date, user_id: @user.id) do %>
              <i class="fas fa-pen"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<!-- Modal　詳細表示及び編集画面遷移用 -->
<%= form_with model: @work, local: true do |f| %>
<div class="modal fade" id="inputModal-edit" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <p></p>
        <h5 class="modal-title" id="exampleModalLabel">日報詳細</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="alert alert-primary" role="alert">
            <span id="modal_day-edit"></span>
          </div>
          <div class="row">
            <div class="col-sm">
              <div class="input-group">
                <%= f.text_field :start_time, id: "modal_start_time-edit", class: "form-control", value: @modal_start_time, readonly: "true" %>
                <div class="input-group-prepend">
                  <button type="button" class="input-group-text">打刻</button>
                </div>
              </div>
            </div>
            <div class="col-sm">
              <div class="input-group">
                <%= f.text_field :end_time, id: "modal_end_time-edit", class: "form-control", value: @modal_end_time, readonly: "true" %>
                <div class="input-group-prepend">
                  <button type="button" class="input-group-text">打刻</button>
                </div>
              </div>
            </div>
            <div class="col-sm">
              <div class="input-group">
                <%= f.text_field :break_time, id: "modal_break_time-edit", class: "form-control rounded", value: @modal_break_time, readonly: "true" %>
              </div>
            </div>
          </div>
          <div class="form-group pt-3">
            <%= f.text_area :comment, id: "modal_comment-edit", class: "form-control", size: "40x5", value: @modal_comment, maxlength: 200, readonly: "true" %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>
<% end %>

<script>
  // 出勤打刻
  $('#start_btn').click(function () {
    const now = new Date();
    const hour = now.getHours().toString().padStart(2, '0');
    const minute = now.getMinutes().toString().padStart(2, '0');
    $('#modal_start_time').val(hour+':'+minute);   
  });
  // 退勤打刻
  $('#end_btn').click(function () {
    const now = new Date();
    const hour = now.getHours().toString().padStart(2, '0');
    const minute = now.getMinutes().toString().padStart(2, '0');
    $('#modal_end_time').val(hour+':'+minute);   
  });

  // 編集モーダル表示
  $('#inputModal-edit').on('show.bs.modal', function(event) {
    const button = $(event.relatedTarget);
    const target_day = button.data('day');
    const target_year = target_day.substr(0, 4)

    // 編集ボタンが押された対象日の表データを取得
    const day = button.closest('tr').children('th')[0].innerText;
    const start_time = button.closest('tr').children('td')[0].innerText;
    const end_time = button.closest('tr').children('td')[1].innerText;
    const break_time = button.closest('tr').children('td')[2].innerText;
    const comment = button.closest('tr').children('td')[3].innerText;

    // 取得したデータをモーダルの各種に設定
    $('#modal_day-edit').text(target_year+ "/" + day);
    $('#modal_start_time-edit').val(start_time);
    $('#modal_end_time-edit').val(end_time);
    $('#modal_break_time-edit').val(break_time);
    $('#modal_comment-edit').val(comment);
    console.log(target_year);
  })
</script>