config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions"
  }
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  root to: "home#index"
  resources :users, only: [:index, :edit, :update, :destroy]
  resources :works
  resources :admin_users, only: [:index]
  resources :admin_works

end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="notication is-info">
    <p class="notice text-white bg-success"><%= notice %></p>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="notication is-danger">
    <p class="alert text-white bg-danger"><%= alert %></p>
  </div>
<% end %> 

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <%= link_to  root_path, class: "navbar-brand" do %>
    <div class="logo">
      <%= image_tag "works-logo.png", class: "logo__img" %>
      <div class="logo__title">WORKS</div>
    </div>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to root_path, class: "nav-link" do %>
          <div class="ham-menu__link-inner">
            <div class="ham-menu__title">ホーム</div>
          </div>
        <% end %>
      </li>
      <% if !admin_signed_in? && !user_signed_in? %>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class: "nav-link" do %>
            <div class="ham-menu__link-inner">
              <div class="ham-menu__title">新規登録(社員)</div>
            </div>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to user_session_path, class: "nav-link" do %>
            <div class="ham-menu__link-inner">
              <div class="ham-menu__title">ログイン(社員)</div>
            </div>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_session_path, class: "nav-link" do %>
            <div class="ham-menu__link-inner">
              <div class="ham-menu__title">ログイン(管理者)</div>
            </div>
          <% end %>
        </li>
      <% end %>
      <% if admin_signed_in? %>
        <li class="nav-item">
          <%= link_to users_path, class: "nav-link" do %>
            <div class="ham-menu__link-inner">
              <div class="ham-menu__title">社員一覧</div>
            </div>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_users_path, class: "nav-link" do %>
            <div class="ham-menu__link-inner">
              <div class="ham-menu__title">管理者一覧</div>
            </div>
          <% end %>
        </li>
        <li>
          <%= link_to new_admin_registration_path, class: "nav-link" do %>
            <div class="ham-menu__link-inner">
              <div class="ham-menu__title">新規登録(管理者)</div>
            </div>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link" do %>
            <div class="ham-menu__link-inner">
              <div class="ham-menu__title">ログアウト(管理者)</div>
            </div>
          <% end %>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to works_path, class: "nav-link" do %>
            <div class="ham-menu__link-inner">
              <div class="ham-menu__title">日報一覧</div>
            </div>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
            <div class="ham-menu__link-inner">
              <div class="ham-menu__title">ログアウト</div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= favicon_link_tag 'apple-touch-icon-180x180.png', rel: 'apple-touch-icon', sizes: '180x180', type: 'image/png' %>
    <%= favicon_link_tag 'android-chrome-192x192.png', rel: 'android-touch-icon', sizes: '192x192', type: 'image/png' %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Staatliches&display=swap" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="text-center bg-info">
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>  
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= favicon_link_tag 'apple-touch-icon-180x180.png', rel: 'apple-touch-icon', sizes: '180x180', type: 'image/png' %>
    <%= favicon_link_tag 'android-chrome-192x192.png', rel: 'android-touch-icon', sizes: '192x192', type: 'image/png' %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Staatliches&display=swap" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="text-center bg-light">
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>  
  </body>
</html>